mc_version=1.21.1
archives_base_name=youtube-chat
mod_version=4.0.2
maven_group=com.stevekung.ytc
parchmentmc_version=1.21.1:2024.11.17
enabled_platforms=fabric

# google libs
api_services_youtube=v3-rev20220612-1.32.1
oauth_client_jetty=1.34.1
api_client=1.35.2
http_client=1.42.1

# fabric
fabric_loader_version=0.16.9
fabric_api_version=0.102.0+1.21.1
modmenu_version=11.0.2
cloth_config_version=15.0.140

# forge
forge_version=52.0.0
configured_version=3721946
catalogue_version=3803098